# Generated by Django 4.0.5 on 2022-06-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Role',
            fields=[
                ('Role_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=20, null=True)),
                ('Last_Name', models.CharField(max_length=20, null=True)),
                ('Email_ID', models.EmailField(max_length=254, null=True)),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Users_Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.user_role')),
            ],
        ),
    ]
