# Generated by Django 4.0.5 on 2022-06-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0003_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='IS_Deleted',
        ),
    ]
