# Generated by Django 4.0.5 on 2022-06-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0005_product_product_sell_price_product_stock_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='Balance',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
