# Generated by Django 4.0.5 on 2022-06-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0006_user_details_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Create_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_purchase',
            name='Purchase_Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
