# Generated by Django 4.0.5 on 2022-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0008_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Cost_Price',
            field=models.PositiveIntegerField(default=True, null=True),
        ),
    ]
